//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityElementAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMaster
    {
        public int Id { get; set; }
        public string UID { get; set; }
        public string CID { get; set; }
    }
}
